In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
emp_data = genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv', delimiter=',', skip_header=1)
print(emp_data)

[[ 1. 22.]
 [ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 8. 23.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [13. 22.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [18. 22.]
 [19. 25.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [23. 24.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [34. 24.]
 [35. 24.]
 [36. 23.]
 [37. 28.]
 [38. 28.]
 [39. 22.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [47. 22.]
 [48. 23.]
 [49. 32.]
 [50. 34.]]


In [3]:
emp_data[:,1]

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

### Find Average Age

In [4]:
avg_age = np.mean(emp_data[:,1])
print("The average age of employees: ", avg_age)

The average age of employees:  28.26


### Find total Number of employees who are over 25 years old

In [10]:


filter_25=emp_data[:,1]>25

In [7]:
emp_data[:,1]

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

### Find employees younger older than 30 and younger than 35

In [ ]:



emp_data[filter_25]

In [14]:
filter_30_35=(emp_data[:,1]>30) & (emp_data[:,1]<35)

In [15]:
emp_data[filter_30_35]

array([[ 3., 31.],
       [10., 32.],
       [16., 33.],
       [32., 32.],
       [41., 32.],
       [43., 33.],
       [44., 31.],
       [49., 32.],
       [50., 34.]])

In [16]:
shop_data = genfromtxt('DS1_C4_S1_Shopping_Data_Challenge (1).csv', delimiter=',', skip_header=1)
print(shop_data)

[[  1.  19.  15.  39.]
 [  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  5.  31.  17.  40.]
 [  6.  22.  17.  76.]
 [  7.  35.  18.   6.]
 [  8.  23.  18.  94.]
 [  9.  64.  19.   3.]
 [ 10.  30.  19.  72.]
 [ 11.  67.  19.  14.]
 [ 12.  35.  19.  99.]
 [ 13.  58.  20.  15.]
 [ 14.  24.  20.  77.]
 [ 15.  37.  20.  13.]
 [ 16.  22.  20.  79.]
 [ 17.  35.  21.  35.]
 [ 18.  20.  21.  66.]
 [ 19.  52.  23.  29.]
 [ 20.  35.  23.  98.]
 [ 21.  35.  24.  35.]
 [ 22.  25.  24.  73.]
 [ 23.  46.  25.   5.]
 [ 24.  31.  25.  73.]
 [ 25.  54.  28.  14.]
 [ 26.  29.  28.  82.]
 [ 27.  45.  28.  32.]
 [ 28.  35.  28.  61.]
 [ 29.  40.  29.  31.]
 [ 30.  23.  29.  87.]
 [ 31.  60.  30.   4.]
 [ 32.  21.  30.  73.]
 [ 33.  53.  33.   4.]
 [ 34.  18.  33.  92.]
 [ 35.  49.  33.  14.]
 [ 36.  21.  33.  81.]
 [ 37.  42.  34.  17.]
 [ 38.  30.  34.  73.]
 [ 39.  36.  37.  26.]
 [ 40.  20.  37.  75.]
 [ 41.  65.  38.  35.]
 [ 42.  24.  38.  92.]
 [ 43.  48.  39.  36.]
 [ 44.  31.

### Find customers whose spending score is more than 80

In [17]:





shop_data[:,3]>80

array([39., 81.,  6., 77., 40., 76.,  6., 94.,  3., 72., 14., 99., 15.,
       77., 13., 79., 35., 66., 29., 98., 35., 73.,  5., 73., 14., 82.,
       32., 61., 31., 87.,  4., 73.,  4., 92., 14., 81., 17., 73., 26.,
       75., 35., 92., 36., 61., 28., 65., 55., 47., 42., 42., 52., 60.,
       54., 60., 45., 41., 50., 46., 51., 46., 56., 55., 52., 59., 51.,
       59., 50., 48., 59., 47., 55., 42., 49., 56., 47., 54., 53., 48.,
       52., 42., 51., 55., 41., 44., 57., 46., 58., 55., 60., 46., 55.,
       41., 49., 40., 42., 52., 47., 50., 42., 49., 41., 48., 59., 55.,
       56., 42., 50., 46., 43., 48., 52., 54., 42., 46., 48., 50., 43.,
       59., 43., 57., 56., 40., 58., 91., 29., 77., 35., 95., 11., 75.,
        9., 75., 34., 71.,  5., 88.,  7., 73., 10., 72.,  5., 93., 40.,
       87., 12., 97., 36., 74., 22., 90., 17., 88., 20., 76., 16., 89.,
        1., 78.,  1., 73., 35., 83.,  5., 93., 26., 75., 20., 95., 27.,
       63., 13., 75., 10., 92., 13., 86., 15., 69., 14., 90., 32

In [18]:
filter_spend_80=shop_data[:,3]>80

In [19]:
shop_data[filter_spend_80]

array([[  2.,  21.,  15.,  81.],
       [  8.,  23.,  18.,  94.],
       [ 12.,  35.,  19.,  99.],
       [ 20.,  35.,  23.,  98.],
       [ 26.,  29.,  28.,  82.],
       [ 30.,  23.,  29.,  87.],
       [ 34.,  18.,  33.,  92.],
       [ 36.,  21.,  33.,  81.],
       [ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [156.,  27.,  78.,  89.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [200.,  30., 137.,  83.]])

### Find customers between agtes 20 and 24

In [25]:
filter_age_20_24=(shop_data[:,1]>=20) & (shop_data[:,1]<=24)

In [26]:
shop_data[filter_age_20_24]

array([[  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  6.,  22.,  17.,  76.],
       [  8.,  23.,  18.,  94.],
       [ 14.,  24.,  20.,  77.],
       [ 16.,  22.,  20.,  79.],
       [ 18.,  20.,  21.,  66.],
       [ 30.,  23.,  29.,  87.],
       [ 32.,  21.,  30.,  73.],
       [ 36.,  21.,  33.,  81.],
       [ 40.,  20.,  37.,  75.],
       [ 42.,  24.,  38.,  92.],
       [ 46.,  24.,  39.,  65.],
       [ 79.,  23.,  54.,  52.],
       [ 85.,  21.,  54.,  57.],
       [ 88.,  22.,  57.,  55.],
       [ 96.,  24.,  60.,  52.],
       [100.,  20.,  61.,  49.],
       [101.,  23.,  62.,  41.],
       [106.,  21.,  62.,  42.],
       [125.,  23.,  70.,  29.],
       [135.,  20.,  73.,   5.]])

### Find customers with highest and lowest incomes

In [34]:


min_row=shop_data[:,2].argmin()
max_row=shop_data[:,2].argmax()
min_cust_id=shop_data[min_row,0]
max_cust_id=shop_data[max_row,0]

print(f"The cusomer id with the the minimum annual income is: {min_cust_id}")
print(f"The cusomer id with the the maximum annual income is: {max_cust_id}")

The cusomer id with the the minimum annual income is: 1.0
The cusomer id with the the maximum annual income is: 199.0


### Find customers spending score over 75 with min salary of 35 and age less than 45

In [38]:


shop_data[(shop_data[:,3]>75) & (shop_data[:,2]>=35) & (shop_data[:,1]<45)]

array([[ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [126.,  31.,  70.,  77.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [154.,  38.,  78.,  76.],
       [156.,  27.,  78.,  89.],
       [158.,  30.,  78.,  78.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [196.,  35., 120.,  79.],
       [200.,  30., 137.,  83.]])

In [44]:
# Task 5 Coupons between 10% and 50%

sz=len(shop_data)

In [45]:
sz

200

In [46]:
np.random.randint(10,50,sz)

array([19, 31, 18, 22, 12, 16, 18, 20, 35, 35, 31, 14, 17, 28, 22, 19, 34,
       29, 12, 41, 39, 24, 12, 26, 47, 31, 30, 15, 35, 26, 30, 36, 22, 44,
       43, 12, 11, 13, 14, 45, 28, 15, 34, 32, 47, 44, 15, 35, 35, 19, 28,
       21, 18, 29, 33, 27, 19, 16, 21, 24, 44, 31, 11, 45, 10, 15, 10, 22,
       25, 44, 35, 36, 28, 11, 40, 18, 42, 28, 22, 15, 19, 30, 31, 18, 45,
       48, 26, 47, 21, 41, 45, 41, 10, 30, 46, 23, 17, 33, 48, 14, 48, 47,
       17, 48, 18, 15, 18, 47, 42, 37, 19, 45, 38, 47, 19, 34, 30, 45, 23,
       21, 21, 29, 34, 29, 20, 13, 39, 38, 25, 34, 20, 39, 19, 21, 10, 11,
       15, 31, 37, 35, 28, 20, 40, 32, 31, 32, 11, 24, 42, 26, 16, 46, 45,
       10, 15, 40, 23, 46, 22, 24, 16, 22, 29, 42, 13, 47, 23, 35, 24, 45,
       38, 22, 19, 47, 37, 29, 39, 30, 12, 23, 45, 41, 36, 24, 39, 10, 49,
       45, 33, 36, 17, 38, 28, 25, 47, 47, 19, 34, 29, 11])

In [49]:
# Task 6 Customers who get more than 45% discount

discounts=np.random.randint(10,50,sz)

In [51]:
np.append(shop_data, discounts[:, None], axis=1)

array([[  1.,  19.,  15.,  39.,  35.],
       [  2.,  21.,  15.,  81.,  38.],
       [  3.,  20.,  16.,   6.,  34.],
       [  4.,  23.,  16.,  77.,  37.],
       [  5.,  31.,  17.,  40.,  32.],
       [  6.,  22.,  17.,  76.,  34.],
       [  7.,  35.,  18.,   6.,  23.],
       [  8.,  23.,  18.,  94.,  16.],
       [  9.,  64.,  19.,   3.,  14.],
       [ 10.,  30.,  19.,  72.,  29.],
       [ 11.,  67.,  19.,  14.,  47.],
       [ 12.,  35.,  19.,  99.,  47.],
       [ 13.,  58.,  20.,  15.,  45.],
       [ 14.,  24.,  20.,  77.,  39.],
       [ 15.,  37.,  20.,  13.,  11.],
       [ 16.,  22.,  20.,  79.,  39.],
       [ 17.,  35.,  21.,  35.,  22.],
       [ 18.,  20.,  21.,  66.,  27.],
       [ 19.,  52.,  23.,  29.,  33.],
       [ 20.,  35.,  23.,  98.,  11.],
       [ 21.,  35.,  24.,  35.,  30.],
       [ 22.,  25.,  24.,  73.,  20.],
       [ 23.,  46.,  25.,   5.,  29.],
       [ 24.,  31.,  25.,  73.,  31.],
       [ 25.,  54.,  28.,  14.,  33.],
       [ 26.,  29.,  28.,

In [ ]:
p_value=pd.Series[]